[Songa] 6주차 미션 완료
ECONO-UNION/union-mentoring-2-iOS pull request #14
Opened 2022-04-15 09:33 UTC by asong57

- 서식지 목록 화면과 서식지별 포켓몬 목록 화면을 구현하였습니다.
  - 서식지 목록 화면은 TableView를 통해 서식지 이름을 나타냈습니다. 테이블의 셀을 클릭하면 해당 서식지의 포켓몬 목록 화면이 나타납니다.
  - 서식지별 포켓몬 목록 화면은 CollectionView를 활용하였습니다. 포켓몬의 이름과 각 이미지로 구성됩니다.
- API 데이터에 맞게 모델을 구성하였습니다. 
  - 서식지 목록 화면 구성을 위해 HabitatListModel, PokemonSpecies 모델을 만들었습니다.
  - 포켓몬 목록 화면 구성을 위해  PokemonModel을 만들었습니다. 포켓몬 각각의 이미지를 얻기 위해 포켓몬 이름에 맞는 id를 얻고자 하는 모델로 id와 name으로 구성했습니다.

2022-04-17 14:27 UTC, seungbong88 requested changes
정말 수고하셨습니다! 이번 미션도 필요한 부분만 깔끔하게 구현 잘해주셨네요! 
변수나 함수명을 정할 때 조금만 더 고민해주시고, 오늘 미팅때 말했던 Generic 을 사용해 네트워크 통신 함수를 공통화하는 방법에 대해 알아보면 좋겠어요! 

추가로 작은 화면에서 실행시켰을 때, 라벨과 이미지, 버튼이 겹치게 되는데 좌우 Constraint 추가해서 수정해주세요. 또 단순 print로 처리하고 있는 예외케이스들을 처리하는 방법에 대해서도 고민해보면 좋을 것 같습니다!
마지막 미션 수고 많으셨고, 함께 열심히 해줘서 정말 감사해요! ❤️‍🔥

2022-04-17 14:27 UTC, seungbong88 commented on songa/PokemonApp/PokemonApp/URLSessionNetwork.swift
> +                }
data 값의 유무만을 가지고 정상 응답여부를 판단하면 서버에러가 발생했을 때 쉽게 알아채지 못하는 경우가 있더라구요. status code를 먼저 판단하는 부분을 추가하면 좋을것 같아요!

2022-04-17 14:27 UTC, seungbong88 commented on songa/PokemonApp/PokemonApp/View/HabitatPokemonViewController.swift
> +    var idList: [String: Int] = [:]
idList라는 이름으로는 포켓몬의 이름과 ID가 대응되는 Dictionary라는 의미가 바로 이해되지 않았어요. 역시 조금 더 구체적인 변수명이 어떤게 있을지 고민해주시고 수정해주세요!

2022-04-17 14:27 UTC, seungbong88 commented on songa/PokemonApp/PokemonApp/View/HabitatPokemonViewController.swift
> +                        self?.collectionView.reloadData()
하나의 셀에 대한 데이터에만 업데이트 하기 때문에, 전체를 Reload 하기보다 해당 셀만 업데이트하는 함수를 사용하는게 더 효율적이에요. 확인하고 수정해주세요~

2022-04-17 14:27 UTC, seungbong88 commented on songa/PokemonApp/PokemonApp/View/HabitatsViewController.swift
> +    func getHabitatListData(id: String){
여기도 역시 get 보다는 다른단어를 사용해서 수정해주세요!

2022-04-17 14:27 UTC, seungbong88 commented on songa/PokemonApp/PokemonApp/URLSessionNetwork.swift
> +    static func fetchApiData(query: String, completion: @escaping (Result<Any, Error>) -> ()){
내용으로는 포켓몬 서식지에 대한 데이터를 가져오는 기능을 하는것에 비해 'fetchApiData' 라는 이름은 다소 추상적이에요. 함수명으로 어떤 기능을 하는지 알기 쉽도록 변경해주세요!

2022-04-17 14:27 UTC, seungbong88 commented on songa/PokemonApp/PokemonApp/View/HabitatsViewController.swift
> +        self.navigationController?.pushViewController(vc, animated: true)
셀을 선택할 때마다 self 의 navigation bar color를 변경해줘야하는 이유가 있나요? 명확한 이유가 없다면 필요할 때에 한 번만 설정해줄 수 있도록 변경해주세요

2022-04-22 19:38 UTC, seungbong88 approved these changes

2022-04-24 12:12 UTC, asong57 commented
피드백 주신 부분 리팩토링하여 수정 완료했습니다!
승희님 최공~!!

2022-04-24 12:12 UTC, merged